### ISSUE TITLE
import with rigify 

### ISSUE THREAD

**Issue by ekswathi** [DreamSpoon/AMH2B#1]
Can we have support for  rigify rig.  Because most of the rigging in blender is done with rigify.  
The addon is amazing and deadly useful. Thank you.

**Comment by DreamSpoon** [comment]
Rigify integration started. Thank you for the specific request, I wasn't sure what rig(s) were most popular.
Should work with Rigify (only tested in 2.79b) - latest download, not in the releases section yet.

**Comment by ekswathi** [comment]
is it working with mfpb? 
http://static.makehumancommunity.org/mpfb.html

**Comment by DreamSpoon** [comment]
Is now working with MPFB2. Supports retarget of Mixamo animations from MPFB2 Mixamo (in MakeHuman default pose) to MPFB2 Default and MPFB2 Rigify.
